---
title: "Chester County Housing Stock"
author: "Dave Drennan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
census_api_key("e13d5be5cb48d927009e0dca0af99d21918d514f", overwrite = TRUE)

theme_cc <- function(){
  font = "sans"
  theme_minimal() %+replace%
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks = element_blank(),
      plot.title = element_text(
        family = font,
        size = 14,
        face = 'bold',
        hjust = 0,
        vjust = 0),
      plot.subtitle = element_text(
        family = font,
        size = 12,
        hjust = 0,
        margin = margin(2, b = 10),
        face = "italic"),
      plot.caption = element_text(
        family = font,
        size = 10,
        hjust = 1),
      axis.title = element_text(
        family = font,
        size = 10,
        margin = margin(5, b = 10)),
      axis.text = element_blank(),
      legend.position = "right",
      legend.text = element_text(
        family = font,
        size = 8)
      )
}
```

```{r}
codes <- c("R-10", # R - Single Family/Cabin
           "R-20", # R - Two Family
           "R-30", # R - Multi Family/Dorms/Single
           "R-40", # A - Apartments (4-19 Units)
           "R-50", # R - Condominium
           "R-55", # R - Town House (Common Law Condo)
           "R-60", # R - Dwelling W/Comm Use Primary R
           "R-61", # C - Dwelling W/Comm Use Primary C
           "R-90") # A - Apt Complex (20 or more units


mobile <- c("R-70", # R - Mobile Home
            "T-10", # R - Trailers and Mobile Homes
            "C-92") # C - Mobile Home Parks (4+)

# Get a list of municipality names in Chester County
municipality_names <- county_subdivisions(42, county = "Chester") %>%
  st_transform(crs = "EPSG:4326") %>%
  pull(NAME)

# Filter data for the current municipality
dat <- read_csv("data/chesco_characteristics_4.2024.csv") %>% 
  select(PARID, WATER, LUC, LUC_desc, YRBLT, COMM_YRBLT, X_CO, Y_CO, situs)

dat <- dat[!is.na(dat$X_CO),]

map_dat <- st_as_sf(dat, coords = c("X_CO", "Y_CO"), crs = "EPSG:2272") %>%
  dplyr::filter(WATER == 1) %>%
  st_transform(crs = "EPSG:4326") %>% 
    mutate(year = dplyr::coalesce(YRBLT, COMM_YRBLT)) %>%
    mutate(if1991 = 
             case_when(year < 1991 ~ "Before 1991",
                       year >= 1991 ~ "1991 or Later"
             ),
           yearGroup = 
             case_when(year > 2010 ~ "2011-2022",
                       year >= 2001 & year < 2011 ~ "2001-2010",
                       year >= 1991 & year < 2001 ~ "1991-2000",
                       year >= 1981 & year < 1991 ~ "1981-1990",
                       year >= 1971 & year < 1981 ~ "1971-1980",
                       year >= 1961 & year < 1971 ~ "1961-1970",
                       year >= 1951 & year < 1961 ~ "1951-1960",
                       year < 1951 ~ "1950 or older"
             )
    )

chester <- county_subdivisions(42, county = "Chester") %>%
    st_transform(crs = "EPSG:4326")  
roads <- roads(state = "PA", county = "Chester") %>%
    st_transform(crs = "EPSG:4326")
water <- area_water(state = "PA", county = "Chester") %>%
    st_transform(crs = "EPSG:4326") 
```

```{r}
# Iterate over each municipality
for (name in municipality_names) {
  
  town <- chester %>%
    dplyr::filter(NAME == name)  
  
  # Transform data into sf objects
  points <- map_dat %>%
    dplyr::filter(LUC %in% codes) %>%
    st_intersection(.,town) %>%
    select(PARID, LUC, LUC_desc, situs, NAME, geometry, year, if1991, yearGroup)
  
  # Transform data into sf objects
  points2 <- map_dat %>%
    dplyr::filter(LUC %in% mobile) %>%
    st_intersection(.,town) %>%
    mutate(yearGroup = "Mobile Home") %>%
    select(PARID, LUC, LUC_desc, situs, NAME, geometry, yearGroup)  
  
  combined <- dplyr::bind_rows(points, points2) %>%
    st_drop_geometry()
  
  bbox <- st_bbox(town)
  bbox_sf <- st_as_sfc(bbox)
  
  town_background <- chester %>%
    st_intersection(., bbox_sf)

  town_water <- water %>%
    st_intersection(., bbox_sf)
  
  town_roads <- roads %>%
    st_intersection(., bbox_sf)

  # Create plot
  plot1 <- ggplot() +
    geom_sf(data = town_background, color = "grey80", fill = "white") +
    geom_sf(data = town_water, fill = "royalblue1", color = "royalblue1") +
    geom_sf(data = town_roads, color = "grey60", lwd = 0.4) +
    geom_sf(data = town_roads, color = "white", lwd = 0.3) +
    geom_sf(data = town, color = "grey20", fill = NA, alpha = 0.7, lwd = 0.5) +
    geom_sf(data = points, aes(color = if1991), alpha = 0.4, size = 0.5) +
    scale_color_manual(values = c("sienna2", "springgreen4", "snow2")) +
    labs(title = name,
         subtitle = "Housing Pre-/Post-1991",
         color = "Year Built") +
    theme_cc()
  
  #plot1

  # Save plot as PNG
  ggsave(paste0("files/", name, "/", name, "_1991.png"), plot = plot1, height = 7, width = 7, dpi = 300)

  # Create plot
  plot2 <- ggplot() +
    geom_sf(data = town_background, color = "grey80", fill = "white") +
    geom_sf(data = town_water, fill = "royalblue1", color = "royalblue1") +
    geom_sf(data = town_roads, color = "grey60", lwd = 0.4) +
    geom_sf(data = town_roads, color = "white", lwd = 0.3) +
    geom_sf(data = town, color = "grey20", fill = NA, alpha = 0.7, lwd = 0.5) +
    geom_sf(data = points, aes(color = yearGroup), alpha = 0.4, size = 0.5) +
    scale_color_viridis_d(option = "turbo") +
    labs(title = name,
         subtitle = "Housing by Decade",
         color = "Year Built") +
    theme_cc()
  
  #plot2

  ggsave(paste0("files/", name, "/", name, "_yearGroup.png"), plot = plot2, height = 7, width = 7, dpi = 300)

  # Create plot
  plot3 <- ggplot() +
    geom_sf(data = town_background, color = "grey80", fill = "white") +
    geom_sf(data = town_water, fill = "royalblue1", color = "royalblue1") +
    geom_sf(data = town_roads, color = "grey60", lwd = 0.4) +
    geom_sf(data = town_roads, color = "white", lwd = 0.3) +
    geom_sf(data = town, color = "grey20", fill = NA, alpha = 0.7, lwd = 0.5) +
    geom_sf(data = points2, aes(color = yearGroup), alpha = 0.4, size = 0.5) +
    scale_color_manual(values = "darkorchid3") +
    labs(title = name,
         subtitle = "Mobile Homes",
         color = "Type") +
    theme_cc() 
  
  #plot3
  
  ggsave(paste0("files/", name, "/", name, "_mobile.png"), plot = plot3, height = 7, width = 7, dpi = 300)
  
  # Save filtered data as CSV
  #write.csv(combined, file = paste0("files/", name, "/", name, ".csv"), row.names = FALSE)
}
```